name: Lint Localizable.strings
author: konifar
description: Checks localization strings across different language files

inputs:
  project-root-path:
    description: "The project root path"
    required: false
    default: "./"
  base-lang-code:
    description: " The base language code to check other language files like 'ja', 'en', prefix of xx.lproj"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Install dependencies
      run: |
        gem install bundler
        cd ${{ github.action_path }}
        bundle install
      shell: bash

    - name: Check apfel installation
      run: bundle show apfel
      shell: bash

    - run: |
        ruby ${{ github.action_path }}/localizable_strings_checker.rb "${{ inputs.project-root-path }}" "${{ inputs.base-lang-code }}"
      shell: bash

branding:
  icon: 'check-square'
  color: 'green'
